// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChatHistory   string
	CustomCommand string
	DiscordServer string
	Song          string
	SongRequest   string
}{
	ChatHistory:   "chat_history",
	CustomCommand: "custom_command",
	DiscordServer: "discord_server",
	Song:          "song",
	SongRequest:   "song_request",
}
