// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChatHistory    string
	CustomCommand  string
	DiscordServer  string
	MutedMembers   string
	RolePermission string
	Song           string
	SongRequest    string
}{
	ChatHistory:    "chat_history",
	CustomCommand:  "custom_command",
	DiscordServer:  "discord_server",
	MutedMembers:   "muted_members",
	RolePermission: "role_permission",
	Song:           "song",
	SongRequest:    "song_request",
}
