// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCustomCommands(t *testing.T) {
	t.Parallel()

	query := CustomCommands()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCustomCommandsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomCommandsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CustomCommands().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomCommandsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CustomCommandSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomCommandsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CustomCommandExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CustomCommand exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CustomCommandExists to return true, but got false.")
	}
}

func testCustomCommandsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	customCommandFound, err := FindCustomCommand(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if customCommandFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCustomCommandsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CustomCommands().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCustomCommandsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CustomCommands().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCustomCommandsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	customCommandOne := &CustomCommand{}
	customCommandTwo := &CustomCommand{}
	if err = randomize.Struct(seed, customCommandOne, customCommandDBTypes, false, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}
	if err = randomize.Struct(seed, customCommandTwo, customCommandDBTypes, false, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = customCommandOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = customCommandTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CustomCommands().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCustomCommandsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	customCommandOne := &CustomCommand{}
	customCommandTwo := &CustomCommand{}
	if err = randomize.Struct(seed, customCommandOne, customCommandDBTypes, false, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}
	if err = randomize.Struct(seed, customCommandTwo, customCommandDBTypes, false, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = customCommandOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = customCommandTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func customCommandBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func customCommandAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomCommand) error {
	*o = CustomCommand{}
	return nil
}

func testCustomCommandsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CustomCommand{}
	o := &CustomCommand{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, customCommandDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CustomCommand object: %s", err)
	}

	AddCustomCommandHook(boil.BeforeInsertHook, customCommandBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	customCommandBeforeInsertHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.AfterInsertHook, customCommandAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	customCommandAfterInsertHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.AfterSelectHook, customCommandAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	customCommandAfterSelectHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.BeforeUpdateHook, customCommandBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	customCommandBeforeUpdateHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.AfterUpdateHook, customCommandAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	customCommandAfterUpdateHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.BeforeDeleteHook, customCommandBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	customCommandBeforeDeleteHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.AfterDeleteHook, customCommandAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	customCommandAfterDeleteHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.BeforeUpsertHook, customCommandBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	customCommandBeforeUpsertHooks = []CustomCommandHook{}

	AddCustomCommandHook(boil.AfterUpsertHook, customCommandAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	customCommandAfterUpsertHooks = []CustomCommandHook{}
}

func testCustomCommandsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCustomCommandsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(customCommandColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCustomCommandToOneDiscordServerUsingGuild(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CustomCommand
	var foreign DiscordServer

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, customCommandDBTypes, false, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, discordServerDBTypes, false, discordServerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DiscordServer struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GuildID = foreign.GuildID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Guild().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.GuildID != foreign.GuildID {
		t.Errorf("want: %v, got %v", foreign.GuildID, check.GuildID)
	}

	slice := CustomCommandSlice{&local}
	if err = local.L.LoadGuild(ctx, tx, false, (*[]*CustomCommand)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Guild = nil
	if err = local.L.LoadGuild(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testCustomCommandToOneSetOpDiscordServerUsingGuild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CustomCommand
	var b, c DiscordServer

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, customCommandDBTypes, false, strmangle.SetComplement(customCommandPrimaryKeyColumns, customCommandColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, discordServerDBTypes, false, strmangle.SetComplement(discordServerPrimaryKeyColumns, discordServerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, discordServerDBTypes, false, strmangle.SetComplement(discordServerPrimaryKeyColumns, discordServerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DiscordServer{&b, &c} {
		err = a.SetGuild(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Guild != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.GuildCustomCommands[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GuildID != x.GuildID {
			t.Error("foreign key was wrong value", a.GuildID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GuildID))
		reflect.Indirect(reflect.ValueOf(&a.GuildID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GuildID != x.GuildID {
			t.Error("foreign key was wrong value", a.GuildID, x.GuildID)
		}
	}
}

func testCustomCommandsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCustomCommandsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CustomCommandSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCustomCommandsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CustomCommands().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	customCommandDBTypes = map[string]string{`ID`: `bigint`, `AddedByUserID`: `text`, `GuildID`: `text`, `CommandName`: `text`, `Message`: `text`, `CreatedAt`: `time with time zone`, `UpdatedAt`: `time with time zone`}
	_                    = bytes.MinRead
)

func testCustomCommandsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(customCommandPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(customCommandAllColumns) == len(customCommandPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCustomCommandsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(customCommandAllColumns) == len(customCommandPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CustomCommand{}
	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, customCommandDBTypes, true, customCommandPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(customCommandAllColumns, customCommandPrimaryKeyColumns) {
		fields = customCommandAllColumns
	} else {
		fields = strmangle.SetComplement(
			customCommandAllColumns,
			customCommandPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CustomCommandSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCustomCommandsUpsert(t *testing.T) {
	t.Parallel()

	if len(customCommandAllColumns) == len(customCommandPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CustomCommand{}
	if err = randomize.Struct(seed, &o, customCommandDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CustomCommand: %s", err)
	}

	count, err := CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, customCommandDBTypes, false, customCommandPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomCommand struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CustomCommand: %s", err)
	}

	count, err = CustomCommands().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
