// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChatHistories", testChatHistoriesUpsert)

	t.Run("CustomCommands", testCustomCommandsUpsert)

	t.Run("DiscordServers", testDiscordServersUpsert)

	t.Run("MutedMembers", testMutedMembersUpsert)

	t.Run("RolePermissions", testRolePermissionsUpsert)

	t.Run("Songs", testSongsUpsert)

	t.Run("SongRequests", testSongRequestsUpsert)
}
