// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Song is an object representing the database table.
type Song struct {
	ID                string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Platform          null.String `boil:"platform" json:"platform,omitempty" toml:"platform" yaml:"platform,omitempty"`
	SongName          string      `boil:"song_name" json:"song_name" toml:"song_name" yaml:"song_name"`
	Description       null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	URL               string      `boil:"url" json:"url" toml:"url" yaml:"url"`
	DurationInSeconds null.Int    `boil:"duration_in_seconds" json:"duration_in_seconds,omitempty" toml:"duration_in_seconds" yaml:"duration_in_seconds,omitempty"`
	IsStream          bool        `boil:"is_stream" json:"is_stream" toml:"is_stream" yaml:"is_stream"`
	ThumbnailURL      null.String `boil:"thumbnail_url" json:"thumbnail_url,omitempty" toml:"thumbnail_url" yaml:"thumbnail_url,omitempty"`
	Artist            null.String `boil:"artist" json:"artist,omitempty" toml:"artist" yaml:"artist,omitempty"`
	Album             null.String `boil:"album" json:"album,omitempty" toml:"album" yaml:"album,omitempty"`
	Track             null.String `boil:"track" json:"track,omitempty" toml:"track" yaml:"track,omitempty"`

	R *songR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L songL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SongColumns = struct {
	ID                string
	Platform          string
	SongName          string
	Description       string
	URL               string
	DurationInSeconds string
	IsStream          string
	ThumbnailURL      string
	Artist            string
	Album             string
	Track             string
}{
	ID:                "id",
	Platform:          "platform",
	SongName:          "song_name",
	Description:       "description",
	URL:               "url",
	DurationInSeconds: "duration_in_seconds",
	IsStream:          "is_stream",
	ThumbnailURL:      "thumbnail_url",
	Artist:            "artist",
	Album:             "album",
	Track:             "track",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var SongWhere = struct {
	ID                whereHelperstring
	Platform          whereHelpernull_String
	SongName          whereHelperstring
	Description       whereHelpernull_String
	URL               whereHelperstring
	DurationInSeconds whereHelpernull_Int
	IsStream          whereHelperbool
	ThumbnailURL      whereHelpernull_String
	Artist            whereHelpernull_String
	Album             whereHelpernull_String
	Track             whereHelpernull_String
}{
	ID:                whereHelperstring{field: "\"song\".\"id\""},
	Platform:          whereHelpernull_String{field: "\"song\".\"platform\""},
	SongName:          whereHelperstring{field: "\"song\".\"song_name\""},
	Description:       whereHelpernull_String{field: "\"song\".\"description\""},
	URL:               whereHelperstring{field: "\"song\".\"url\""},
	DurationInSeconds: whereHelpernull_Int{field: "\"song\".\"duration_in_seconds\""},
	IsStream:          whereHelperbool{field: "\"song\".\"is_stream\""},
	ThumbnailURL:      whereHelpernull_String{field: "\"song\".\"thumbnail_url\""},
	Artist:            whereHelpernull_String{field: "\"song\".\"artist\""},
	Album:             whereHelpernull_String{field: "\"song\".\"album\""},
	Track:             whereHelpernull_String{field: "\"song\".\"track\""},
}

// SongRels is where relationship names are stored.
var SongRels = struct {
	SongRequests string
}{
	SongRequests: "SongRequests",
}

// songR is where relationships are stored.
type songR struct {
	SongRequests SongRequestSlice
}

// NewStruct creates a new relationship struct
func (*songR) NewStruct() *songR {
	return &songR{}
}

// songL is where Load methods for each relationship are stored.
type songL struct{}

var (
	songAllColumns            = []string{"id", "platform", "song_name", "description", "url", "duration_in_seconds", "is_stream", "thumbnail_url", "artist", "album", "track"}
	songColumnsWithoutDefault = []string{"id", "platform", "song_name", "description", "url", "duration_in_seconds", "is_stream", "thumbnail_url", "artist", "album", "track"}
	songColumnsWithDefault    = []string{}
	songPrimaryKeyColumns     = []string{"id"}
)

type (
	// SongSlice is an alias for a slice of pointers to Song.
	// This should generally be used opposed to []Song.
	SongSlice []*Song
	// SongHook is the signature for custom Song hook methods
	SongHook func(context.Context, boil.ContextExecutor, *Song) error

	songQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	songType                 = reflect.TypeOf(&Song{})
	songMapping              = queries.MakeStructMapping(songType)
	songPrimaryKeyMapping, _ = queries.BindMapping(songType, songMapping, songPrimaryKeyColumns)
	songInsertCacheMut       sync.RWMutex
	songInsertCache          = make(map[string]insertCache)
	songUpdateCacheMut       sync.RWMutex
	songUpdateCache          = make(map[string]updateCache)
	songUpsertCacheMut       sync.RWMutex
	songUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var songBeforeInsertHooks []SongHook
var songBeforeUpdateHooks []SongHook
var songBeforeDeleteHooks []SongHook
var songBeforeUpsertHooks []SongHook

var songAfterInsertHooks []SongHook
var songAfterSelectHooks []SongHook
var songAfterUpdateHooks []SongHook
var songAfterDeleteHooks []SongHook
var songAfterUpsertHooks []SongHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Song) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Song) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Song) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Song) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Song) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Song) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Song) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Song) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Song) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range songAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSongHook registers your hook function for all future operations.
func AddSongHook(hookPoint boil.HookPoint, songHook SongHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		songBeforeInsertHooks = append(songBeforeInsertHooks, songHook)
	case boil.BeforeUpdateHook:
		songBeforeUpdateHooks = append(songBeforeUpdateHooks, songHook)
	case boil.BeforeDeleteHook:
		songBeforeDeleteHooks = append(songBeforeDeleteHooks, songHook)
	case boil.BeforeUpsertHook:
		songBeforeUpsertHooks = append(songBeforeUpsertHooks, songHook)
	case boil.AfterInsertHook:
		songAfterInsertHooks = append(songAfterInsertHooks, songHook)
	case boil.AfterSelectHook:
		songAfterSelectHooks = append(songAfterSelectHooks, songHook)
	case boil.AfterUpdateHook:
		songAfterUpdateHooks = append(songAfterUpdateHooks, songHook)
	case boil.AfterDeleteHook:
		songAfterDeleteHooks = append(songAfterDeleteHooks, songHook)
	case boil.AfterUpsertHook:
		songAfterUpsertHooks = append(songAfterUpsertHooks, songHook)
	}
}

// One returns a single song record from the query.
func (q songQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Song, error) {
	o := &Song{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for song")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Song records from the query.
func (q songQuery) All(ctx context.Context, exec boil.ContextExecutor) (SongSlice, error) {
	var o []*Song

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Song slice")
	}

	if len(songAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Song records in the query.
func (q songQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count song rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q songQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if song exists")
	}

	return count > 0, nil
}

// SongRequests retrieves all the song_request's SongRequests with an executor.
func (o *Song) SongRequests(mods ...qm.QueryMod) songRequestQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"song_request\".\"song_id\"=?", o.ID),
	)

	query := SongRequests(queryMods...)
	queries.SetFrom(query.Query, "\"song_request\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"song_request\".*"})
	}

	return query
}

// LoadSongRequests allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (songL) LoadSongRequests(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSong interface{}, mods queries.Applicator) error {
	var slice []*Song
	var object *Song

	if singular {
		object = maybeSong.(*Song)
	} else {
		slice = *maybeSong.(*[]*Song)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &songR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &songR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`song_request`), qm.WhereIn(`song_request.song_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load song_request")
	}

	var resultSlice []*SongRequest
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice song_request")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on song_request")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for song_request")
	}

	if len(songRequestAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SongRequests = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &songRequestR{}
			}
			foreign.R.Song = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.SongID) {
				local.R.SongRequests = append(local.R.SongRequests, foreign)
				if foreign.R == nil {
					foreign.R = &songRequestR{}
				}
				foreign.R.Song = local
				break
			}
		}
	}

	return nil
}

// AddSongRequests adds the given related objects to the existing relationships
// of the song, optionally inserting them as new records.
// Appends related to o.R.SongRequests.
// Sets related.R.Song appropriately.
func (o *Song) AddSongRequests(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SongRequest) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SongID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"song_request\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"song_id"}),
				strmangle.WhereClause("\"", "\"", 2, songRequestPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SongID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &songR{
			SongRequests: related,
		}
	} else {
		o.R.SongRequests = append(o.R.SongRequests, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &songRequestR{
				Song: o,
			}
		} else {
			rel.R.Song = o
		}
	}
	return nil
}

// SetSongRequests removes all previously related items of the
// song replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Song's SongRequests accordingly.
// Replaces o.R.SongRequests with related.
// Sets related.R.Song's SongRequests accordingly.
func (o *Song) SetSongRequests(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SongRequest) error {
	query := "update \"song_request\" set \"song_id\" = null where \"song_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SongRequests {
			queries.SetScanner(&rel.SongID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Song = nil
		}

		o.R.SongRequests = nil
	}
	return o.AddSongRequests(ctx, exec, insert, related...)
}

// RemoveSongRequests relationships from objects passed in.
// Removes related items from R.SongRequests (uses pointer comparison, removal does not keep order)
// Sets related.R.Song.
func (o *Song) RemoveSongRequests(ctx context.Context, exec boil.ContextExecutor, related ...*SongRequest) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SongID, nil)
		if rel.R != nil {
			rel.R.Song = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("song_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SongRequests {
			if rel != ri {
				continue
			}

			ln := len(o.R.SongRequests)
			if ln > 1 && i < ln-1 {
				o.R.SongRequests[i] = o.R.SongRequests[ln-1]
			}
			o.R.SongRequests = o.R.SongRequests[:ln-1]
			break
		}
	}

	return nil
}

// Songs retrieves all the records using an executor.
func Songs(mods ...qm.QueryMod) songQuery {
	mods = append(mods, qm.From("\"song\""))
	return songQuery{NewQuery(mods...)}
}

// FindSong retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSong(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Song, error) {
	songObj := &Song{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"song\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, songObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from song")
	}

	return songObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Song) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no song provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(songColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	songInsertCacheMut.RLock()
	cache, cached := songInsertCache[key]
	songInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			songAllColumns,
			songColumnsWithDefault,
			songColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(songType, songMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(songType, songMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"song\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"song\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into song")
	}

	if !cached {
		songInsertCacheMut.Lock()
		songInsertCache[key] = cache
		songInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Song.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Song) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	songUpdateCacheMut.RLock()
	cache, cached := songUpdateCache[key]
	songUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			songAllColumns,
			songPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update song, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"song\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, songPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(songType, songMapping, append(wl, songPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update song row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for song")
	}

	if !cached {
		songUpdateCacheMut.Lock()
		songUpdateCache[key] = cache
		songUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q songQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for song")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for song")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SongSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), songPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"song\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, songPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in song slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all song")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Song) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no song provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(songColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	songUpsertCacheMut.RLock()
	cache, cached := songUpsertCache[key]
	songUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			songAllColumns,
			songColumnsWithDefault,
			songColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			songAllColumns,
			songPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert song, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(songPrimaryKeyColumns))
			copy(conflict, songPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"song\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(songType, songMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(songType, songMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert song")
	}

	if !cached {
		songUpsertCacheMut.Lock()
		songUpsertCache[key] = cache
		songUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Song record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Song) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Song provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), songPrimaryKeyMapping)
	sql := "DELETE FROM \"song\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from song")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for song")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q songQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no songQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from song")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for song")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SongSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(songBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), songPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"song\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, songPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from song slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for song")
	}

	if len(songAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Song) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSong(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SongSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SongSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), songPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"song\".* FROM \"song\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, songPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SongSlice")
	}

	*o = slice

	return nil
}

// SongExists checks if the Song row exists.
func SongExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"song\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if song exists")
	}

	return exists, nil
}
